import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/home/NavBar";
import Footer from "@/component/home/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        <main className="mt-16 flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
